[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
command = "tuigreet --issue --time --remember --window-padding 1 --theme 'container=darkgray;border=lightmagenta;text=lightcyan;prompt=lightcyan;input=lightcyan;greet=cyan;time=lightmagenta;action=gray;button=darkgray'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
